---
- name: "Build container with ansible"
  hosts: localhost
  tasks:
  - name: stop running container
    command: docker stop toxreader/mypage
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm toxreader/mypage
    ignore_errors: yes
  
  - name: remove used image
    command: docker rmi toxreader/mypage
    ignore_errors: yes
    
  - name: build docker image from dockerfile
    command: docker build -t toxreader/mypage .  

  - name: create tag to image
    command: docker tag toxreader/mypage toxreader/mypage

  - name: push image to dockerhub
    command: docker push toxreader/mypage 

  - name: run container from image
    command: docker run -d --name my-docker-container -p 8008:80 toxreader/mypage