---
- name: "Build container with ansible"
  hosts: localhost
  tasks:
  - name: stop running container
    command: docker stop mypage-container
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm mypage-container
    ignore_errors: yes
  
  - name: remove used image
    command: docker rmi mypage-image
    ignore_errors: yes
    
  - name: build docker image from dockerfile
    command: docker build -t mypage-image .  

  - name: run container from image
    command: docker run -d --name mypage-container -p 8008:80 mypage-image